import Head from 'next/head'
import Portfolio from "./Portfolio";



export default function Home() {
  return (
    <>
      <Head>
        <title>Mi Portafolio - Desarrollador</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Portfolio/>

    </>
  )
}
